[package]
name = "burn_sample"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.0", features = ["train", "wgpu", "vision"] }
clap = { version = "4.5.37", features = ["derive"] }
